STRI e125:
  sensors:
  - type: ZigBee
    udp_listen_port: 5000
  map:
    base: RobotHouseMap.svg
    svg_scale: 0.275
    svg_offset:
      x: 81
      y: 245
    svg_rotation: -90
    pgm_scale: 0.05
    pgm_offset:
      x: 0
      y: 0