UH Robot House:
  sensors:
  - type: ZigBee
    udp_listen_port: 5000
  - type: GEOSystem
    geo_server: geo-eee-pc
    geo_user: guest
    geo_password: r0b0th0use##
    geo_db: livewiredb
    geo_query: CALL expPower
  - type: ZWaveHomeController
    zwave_ip: 10.0.1.113
  #- type: ZigBeeDirect
  #  usb_port: /dev/ttyUSB0
  map:
    base: RobotHouseMap.svg
    svg_scale: 100.0
    svg_offset: 
      x: 402.5
      y: 999.75
    svg_rotation: 90
    pgm_scale: 0.05
    pgm_offset:
      x: -8
      y: -19.2
