UH Robot House:
  sensors:
  - type: ZigBee
    udp_listen_port: 5000
  - type: GEOSystem
    geo_server: geo-eee-pc
    geo_user: guest
    geo_password: r0b0th0use##
    geo_db: livewiredb
    geo_query: CALL expPower
  #- type: ZigBeeDirect
  #  usb_port: /dev/ttyUSB0
  map:
    base: RobotHouseMap.svg
    svg_scale: 27.0
    svg_offset:
      x: 110
      y: 1240
    svg_rotation: 0
    pgm_scale: 0.05
    pgm_offset:
      x: -8
      y: -19.2

    #svg_scale: 28
    #svg_offset:
      #x: 120
      #y: 1230
