UH Robot House:
  sensors:
  - type: ZigBee
    udp_listen_port: 5000
  - type: GEOSystem
    geo_server: geo-eee-pc
    geo_user: guest
    geo_password: r0b0th0use##
    geo_db: livewiredb
    geo_query: CALL expPower
  #- type: ZigBeeDirect
  #  usb_port: /dev/ttyUSB0
  map:
    base: RobotHouseMap.svg
    svg_scale: 0.275
    svg_offset: 
      x: 81
      y: 245
    svg_rotation: -90
    pgm_scale: 0.05
    pgm_offset:
      x: -8
      y: -19.2