DROP TABLE IF EXISTS SensorVector;

delimiter $$

CREATE TABLE `SensorVector` (
  `lastUpdate` datetime NOT NULL COMMENT 'Last time the sensor state was updated',
  `sensorLocation` text NOT NULL COMMENT 'The location of the last sensor fired',
  `sensor1` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor2` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor3` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor4` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor5` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor6` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor7` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor8` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor9` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor10` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor11` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor12` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor13` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor14` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor15` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor16` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor17` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor18` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor19` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor20` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor21` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor22` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor23` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor24` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor25` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor26` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor27` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor28` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor29` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor30` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor31` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor32` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor33` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor34` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor35` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor36` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor37` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor38` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor39` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor40` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor41` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor42` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor43` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor44` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor45` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor46` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor47` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor48` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor49` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor50` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor51` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor52` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor53` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor54` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor55` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor56` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor57` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor58` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor59` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `sensor60` text NOT NULL COMMENT 'The sensor value e.g. on/off',
  `lastSensorId` text NOT NULL,
  `classification` text NOT NULL,
  PRIMARY KEY (`lastUpdate`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Holds flat table of sensor states'$$
delimiter $$;
