/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Wed Jul 16 10:58:35 2014
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListView>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSpinBox>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTimeEdit>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *teachMePushButton;
    QPushButton *showMePushButton;
    QPushButton *startLearningPushButton;
    QPushButton *stopLearningPushButton;
    QPushButton *cancelPushButton;
    QLabel *learningStartedLabel;
    QTabWidget *alreadyKnowWidget;
    QWidget *tab;
    QListView *allKnowHowListView;
    QLabel *knowHowLabel;
    QPushButton *everythingLearnItPushButton;
    QWidget *tab_4;
    QListView *moveKnowHowListView;
    QLabel *knowHowLabel_4;
    QPushButton *moveLearnItPushButton;
    QComboBox *moveComboBox;
    QLabel *label_2;
    QWidget *tab_2;
    QListView *speakKnowHowListView;
    QLabel *knowHowLabel_2;
    QLineEdit *speakLineEdit;
    QLabel *label;
    QPushButton *speakLearnItPushButton;
    QWidget *tab_17;
    QListView *trayTorsoKnowHowListView;
    QLabel *knowHowLabel_5;
    QPushButton *trayLearnItPushButton;
    QWidget *tab_6;
    QWidget *tab_3;
    QPushButton *whenTellMePushButton;
    QLabel *label_3;
    QPushButton *whenSomethingPushButton;
    QPushButton *doingPushButton;
    QPushButton *locationPushButton;
    QPushButton *timePushButton;
    QPushButton *okPushButton;
    QWidget *tab_16;
    QLabel *label_16;
    QPushButton *toldFinishedPushButton;
    QWidget *tab_9;
    QTabWidget *tabWidget;
    QWidget *tab_10;
    QCheckBox *sittingTableCheckBox;
    QCheckBox *bigCupboardCheckBox;
    QCheckBox *smallCupboardCheckBox;
    QPushButton *diningLearnItPushButton;
    QWidget *tab_11;
    QCheckBox *sittingSofaCheckBox;
    QCheckBox *TVOncheckBox;
    QPushButton *livingLearnItPushButton;
    QWidget *tab_12;
    QCheckBox *kitechCupboadsCheckBox;
    QCheckBox *kitchenTapsCheckBox;
    QPushButton *kitchenLearnItPushButton;
    QWidget *tab_13;
    QCheckBox *microwaveCheckBox;
    QCheckBox *fridgeCheckBox;
    QCheckBox *doorbellCheckBox;
    QPushButton *ElectricalLearnItPushButton;
    QWidget *tab_14;
    QCheckBox *bathTapsCheckBox;
    QPushButton *BathroomLearnItPushButton;
    QCheckBox *bathDoorCheckBox;
    QCheckBox *bathFlushCheckBox;
    QLabel *label_5;
    QSpinBox *happeningSpinBox;
    QLabel *label_11;
    QLabel *label_12;
    QSpinBox *hasHappendedSpinBox;
    QLabel *label_21;
    QPushButton *houseFinishedPushButton;
    QWidget *tab_15;
    QComboBox *contextComboBox;
    QLabel *label_15;
    QPushButton *contextLearnItPushButton;
    QPushButton *contextFinishedPushButton;
    QLabel *label_20;
    QSpinBox *contextHappeningSpinBox;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QSpinBox *contextHasHappendedSpinBox;
    QWidget *tab_7;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_13;
    QComboBox *userLocnComboBox;
    QComboBox *andRobotLocnComboBox;
    QPushButton *locationLearnItPushButton;
    QListView *locationListView;
    QLabel *knowHowLabel_8;
    QPushButton *locnFinishedPushButton;
    QWidget *tab_5;
    QPushButton *timeLearnItPushButton;
    QLabel *label_7;
    QLabel *label_8;
    QTimeEdit *AtTimeEdit;
    QTimeEdit *betweenToTimeEdit;
    QTimeEdit *betweenFromTimeEdit;
    QGroupBox *groupBox;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QRadioButton *radioButton_3;
    QGroupBox *groupBox_3;
    QCheckBox *atCheckBox;
    QCheckBox *betweenCheckBox;
    QGroupBox *groupBox_4;
    QRadioButton *radioButton_9;
    QRadioButton *radioButton_10;
    QRadioButton *radioButton_11;
    QRadioButton *radioButton_12;
    QLabel *label_4;
    QGroupBox *groupBox_2;
    QCheckBox *mondayCheckBox;
    QCheckBox *tuesdayCheckBox;
    QCheckBox *wednesdayCheckBox;
    QCheckBox *ThursdayCheckBox;
    QCheckBox *fridayCheckBox;
    QCheckBox *saturdayCheckBox;
    QCheckBox *sundayCheckBox;
    QLabel *label_17;
    QSpinBox *everyNdaysSpinBox;
    QLabel *label_18;
    QLabel *label_23;
    QSpinBox *everyNHoursSpinBox;
    QLabel *label_22;
    QPushButton *timeFinishedPushButton;
    QLabel *label_6;
    QFrame *line;
    QWidget *tab_18;
    QLabel *label_24;
    QSpinBox *resetSpinBox;
    QCheckBox *alwaysCheckBox;
    QLabel *label_19;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QPushButton *repeatFinishedPushButton;
    QPushButton *repeatLearnItPushButton;
    QWidget *tab_8;
    QLabel *label_14;
    QListView *finalListView;
    QPushButton *finalRememberPushButton;
    QPushButton *allDonePushButton;
    QLabel *learnedSoFarLabel;
    QLabel *dbLabel;
    QComboBox *behNameComboBox;
    QPushButton *addPushButton;
    QPushButton *deletePushButton;
    QPushButton *rememberThisPushButton;
    QLineEdit *behNameLineEdit;
    QListWidget *learnedSoFarListWidget;
    QLabel *nickName;
    QPushButton *whatPushButton;
    QPushButton *whenPushButton;
    QPushButton *whatPushButton_2;
    QPushButton *whenPushButton_2;
    QLabel *arrow1;
    QPushButton *finishedB;
    QPushButton *finsihedB2;
    QLabel *arrow2;
    QPushButton *changePushButton;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1129, 732);
        QFont font;
        font.setFamily(QString::fromUtf8("Sans Serif"));
        font.setPointSize(14);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QString::fromUtf8("background-color: rgb(220, 220, 220);\n"
"font: 14pt \"Sans Serif\";"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        teachMePushButton = new QPushButton(centralWidget);
        teachMePushButton->setObjectName(QString::fromUtf8("teachMePushButton"));
        teachMePushButton->setGeometry(QRect(10, 0, 231, 41));
        teachMePushButton->setFont(font);
        showMePushButton = new QPushButton(centralWidget);
        showMePushButton->setObjectName(QString::fromUtf8("showMePushButton"));
        showMePushButton->setGeometry(QRect(240, 0, 191, 41));
        showMePushButton->setFont(font);
        startLearningPushButton = new QPushButton(centralWidget);
        startLearningPushButton->setObjectName(QString::fromUtf8("startLearningPushButton"));
        startLearningPushButton->setEnabled(true);
        startLearningPushButton->setGeometry(QRect(920, 290, 181, 51));
        startLearningPushButton->setFont(font);
        startLearningPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 128, 0);"));
        stopLearningPushButton = new QPushButton(centralWidget);
        stopLearningPushButton->setObjectName(QString::fromUtf8("stopLearningPushButton"));
        stopLearningPushButton->setEnabled(true);
        stopLearningPushButton->setGeometry(QRect(860, 260, 261, 51));
        stopLearningPushButton->setFont(font);
        stopLearningPushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
""));
        cancelPushButton = new QPushButton(centralWidget);
        cancelPushButton->setObjectName(QString::fromUtf8("cancelPushButton"));
        cancelPushButton->setEnabled(true);
        cancelPushButton->setGeometry(QRect(710, 50, 181, 31));
        cancelPushButton->setFont(font);
        learningStartedLabel = new QLabel(centralWidget);
        learningStartedLabel->setObjectName(QString::fromUtf8("learningStartedLabel"));
        learningStartedLabel->setGeometry(QRect(730, 150, 331, 21));
        learningStartedLabel->setFont(font);
        alreadyKnowWidget = new QTabWidget(centralWidget);
        alreadyKnowWidget->setObjectName(QString::fromUtf8("alreadyKnowWidget"));
        alreadyKnowWidget->setEnabled(true);
        alreadyKnowWidget->setGeometry(QRect(20, 140, 691, 421));
        alreadyKnowWidget->setAutoFillBackground(false);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        allKnowHowListView = new QListView(tab);
        allKnowHowListView->setObjectName(QString::fromUtf8("allKnowHowListView"));
        allKnowHowListView->setGeometry(QRect(20, 30, 631, 281));
        knowHowLabel = new QLabel(tab);
        knowHowLabel->setObjectName(QString::fromUtf8("knowHowLabel"));
        knowHowLabel->setGeometry(QRect(190, 10, 251, 16));
        knowHowLabel->setFont(font);
        everythingLearnItPushButton = new QPushButton(tab);
        everythingLearnItPushButton->setObjectName(QString::fromUtf8("everythingLearnItPushButton"));
        everythingLearnItPushButton->setGeometry(QRect(230, 320, 211, 41));
        everythingLearnItPushButton->setFont(font);
        everythingLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        alreadyKnowWidget->addTab(tab, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        moveKnowHowListView = new QListView(tab_4);
        moveKnowHowListView->setObjectName(QString::fromUtf8("moveKnowHowListView"));
        moveKnowHowListView->setGeometry(QRect(50, 50, 571, 191));
        knowHowLabel_4 = new QLabel(tab_4);
        knowHowLabel_4->setObjectName(QString::fromUtf8("knowHowLabel_4"));
        knowHowLabel_4->setGeometry(QRect(230, 20, 261, 16));
        knowHowLabel_4->setFont(font);
        moveLearnItPushButton = new QPushButton(tab_4);
        moveLearnItPushButton->setObjectName(QString::fromUtf8("moveLearnItPushButton"));
        moveLearnItPushButton->setGeometry(QRect(230, 320, 211, 41));
        moveLearnItPushButton->setFont(font);
        moveLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        moveComboBox = new QComboBox(tab_4);
        moveComboBox->setObjectName(QString::fromUtf8("moveComboBox"));
        moveComboBox->setGeometry(QRect(60, 280, 551, 41));
        moveComboBox->setFont(font);
        moveComboBox->setEditable(false);
        label_2 = new QLabel(tab_4);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(180, 260, 281, 16));
        alreadyKnowWidget->addTab(tab_4, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        speakKnowHowListView = new QListView(tab_2);
        speakKnowHowListView->setObjectName(QString::fromUtf8("speakKnowHowListView"));
        speakKnowHowListView->setGeometry(QRect(30, 30, 611, 201));
        knowHowLabel_2 = new QLabel(tab_2);
        knowHowLabel_2->setObjectName(QString::fromUtf8("knowHowLabel_2"));
        knowHowLabel_2->setGeometry(QRect(200, 10, 271, 16));
        knowHowLabel_2->setFont(font);
        speakLineEdit = new QLineEdit(tab_2);
        speakLineEdit->setObjectName(QString::fromUtf8("speakLineEdit"));
        speakLineEdit->setGeometry(QRect(260, 240, 381, 41));
        label = new QLabel(tab_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 250, 231, 16));
        speakLearnItPushButton = new QPushButton(tab_2);
        speakLearnItPushButton->setObjectName(QString::fromUtf8("speakLearnItPushButton"));
        speakLearnItPushButton->setGeometry(QRect(240, 300, 211, 41));
        speakLearnItPushButton->setFont(font);
        speakLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        alreadyKnowWidget->addTab(tab_2, QString());
        tab_17 = new QWidget();
        tab_17->setObjectName(QString::fromUtf8("tab_17"));
        trayTorsoKnowHowListView = new QListView(tab_17);
        trayTorsoKnowHowListView->setObjectName(QString::fromUtf8("trayTorsoKnowHowListView"));
        trayTorsoKnowHowListView->setGeometry(QRect(50, 60, 571, 191));
        knowHowLabel_5 = new QLabel(tab_17);
        knowHowLabel_5->setObjectName(QString::fromUtf8("knowHowLabel_5"));
        knowHowLabel_5->setGeometry(QRect(240, 30, 261, 16));
        knowHowLabel_5->setFont(font);
        trayLearnItPushButton = new QPushButton(tab_17);
        trayLearnItPushButton->setObjectName(QString::fromUtf8("trayLearnItPushButton"));
        trayLearnItPushButton->setGeometry(QRect(220, 300, 211, 41));
        trayLearnItPushButton->setFont(font);
        trayLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        alreadyKnowWidget->addTab(tab_17, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        alreadyKnowWidget->addTab(tab_6, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        whenTellMePushButton = new QPushButton(tab_3);
        whenTellMePushButton->setObjectName(QString::fromUtf8("whenTellMePushButton"));
        whenTellMePushButton->setEnabled(false);
        whenTellMePushButton->setGeometry(QRect(230, 290, 291, 51));
        whenTellMePushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(220, 220, 220);"));
        whenTellMePushButton->setCheckable(true);
        label_3 = new QLabel(tab_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 10, 151, 16));
        whenSomethingPushButton = new QPushButton(tab_3);
        whenSomethingPushButton->setObjectName(QString::fromUtf8("whenSomethingPushButton"));
        whenSomethingPushButton->setGeometry(QRect(130, 110, 511, 51));
        whenSomethingPushButton->setCheckable(true);
        doingPushButton = new QPushButton(tab_3);
        doingPushButton->setObjectName(QString::fromUtf8("doingPushButton"));
        doingPushButton->setEnabled(true);
        doingPushButton->setGeometry(QRect(130, 50, 511, 51));
        doingPushButton->setCheckable(true);
        locationPushButton = new QPushButton(tab_3);
        locationPushButton->setObjectName(QString::fromUtf8("locationPushButton"));
        locationPushButton->setGeometry(QRect(130, 170, 511, 51));
        locationPushButton->setCheckable(true);
        timePushButton = new QPushButton(tab_3);
        timePushButton->setObjectName(QString::fromUtf8("timePushButton"));
        timePushButton->setGeometry(QRect(130, 230, 511, 51));
        timePushButton->setCheckable(true);
        okPushButton = new QPushButton(tab_3);
        okPushButton->setObjectName(QString::fromUtf8("okPushButton"));
        okPushButton->setGeometry(QRect(30, 300, 131, 51));
        alreadyKnowWidget->addTab(tab_3, QString());
        doingPushButton->raise();
        whenTellMePushButton->raise();
        label_3->raise();
        whenSomethingPushButton->raise();
        locationPushButton->raise();
        timePushButton->raise();
        okPushButton->raise();
        tab_16 = new QWidget();
        tab_16->setObjectName(QString::fromUtf8("tab_16"));
        label_16 = new QLabel(tab_16);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(150, 130, 431, 101));
        toldFinishedPushButton = new QPushButton(tab_16);
        toldFinishedPushButton->setObjectName(QString::fromUtf8("toldFinishedPushButton"));
        toldFinishedPushButton->setGeometry(QRect(240, 250, 191, 41));
        toldFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        toldFinishedPushButton->setCheckable(true);
        alreadyKnowWidget->addTab(tab_16, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        tabWidget = new QTabWidget(tab_9);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(50, 10, 551, 291));
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        sittingTableCheckBox = new QCheckBox(tab_10);
        sittingTableCheckBox->setObjectName(QString::fromUtf8("sittingTableCheckBox"));
        sittingTableCheckBox->setGeometry(QRect(70, 30, 341, 23));
        bigCupboardCheckBox = new QCheckBox(tab_10);
        bigCupboardCheckBox->setObjectName(QString::fromUtf8("bigCupboardCheckBox"));
        bigCupboardCheckBox->setGeometry(QRect(70, 80, 421, 23));
        smallCupboardCheckBox = new QCheckBox(tab_10);
        smallCupboardCheckBox->setObjectName(QString::fromUtf8("smallCupboardCheckBox"));
        smallCupboardCheckBox->setGeometry(QRect(70, 130, 441, 23));
        diningLearnItPushButton = new QPushButton(tab_10);
        diningLearnItPushButton->setObjectName(QString::fromUtf8("diningLearnItPushButton"));
        diningLearnItPushButton->setGeometry(QRect(160, 190, 211, 41));
        diningLearnItPushButton->setFont(font);
        diningLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_10, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QString::fromUtf8("tab_11"));
        sittingSofaCheckBox = new QCheckBox(tab_11);
        sittingSofaCheckBox->setObjectName(QString::fromUtf8("sittingSofaCheckBox"));
        sittingSofaCheckBox->setGeometry(QRect(120, 50, 341, 23));
        TVOncheckBox = new QCheckBox(tab_11);
        TVOncheckBox->setObjectName(QString::fromUtf8("TVOncheckBox"));
        TVOncheckBox->setGeometry(QRect(120, 100, 161, 23));
        livingLearnItPushButton = new QPushButton(tab_11);
        livingLearnItPushButton->setObjectName(QString::fromUtf8("livingLearnItPushButton"));
        livingLearnItPushButton->setGeometry(QRect(160, 200, 211, 41));
        livingLearnItPushButton->setFont(font);
        livingLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_11, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QString::fromUtf8("tab_12"));
        kitechCupboadsCheckBox = new QCheckBox(tab_12);
        kitechCupboadsCheckBox->setObjectName(QString::fromUtf8("kitechCupboadsCheckBox"));
        kitechCupboadsCheckBox->setGeometry(QRect(60, 50, 341, 23));
        kitchenTapsCheckBox = new QCheckBox(tab_12);
        kitchenTapsCheckBox->setObjectName(QString::fromUtf8("kitchenTapsCheckBox"));
        kitchenTapsCheckBox->setGeometry(QRect(60, 100, 341, 23));
        kitchenLearnItPushButton = new QPushButton(tab_12);
        kitchenLearnItPushButton->setObjectName(QString::fromUtf8("kitchenLearnItPushButton"));
        kitchenLearnItPushButton->setGeometry(QRect(170, 190, 211, 41));
        kitchenLearnItPushButton->setFont(font);
        kitchenLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_12, QString());
        tab_13 = new QWidget();
        tab_13->setObjectName(QString::fromUtf8("tab_13"));
        microwaveCheckBox = new QCheckBox(tab_13);
        microwaveCheckBox->setObjectName(QString::fromUtf8("microwaveCheckBox"));
        microwaveCheckBox->setGeometry(QRect(80, 20, 391, 23));
        fridgeCheckBox = new QCheckBox(tab_13);
        fridgeCheckBox->setObjectName(QString::fromUtf8("fridgeCheckBox"));
        fridgeCheckBox->setGeometry(QRect(80, 80, 391, 23));
        doorbellCheckBox = new QCheckBox(tab_13);
        doorbellCheckBox->setObjectName(QString::fromUtf8("doorbellCheckBox"));
        doorbellCheckBox->setGeometry(QRect(80, 140, 361, 23));
        ElectricalLearnItPushButton = new QPushButton(tab_13);
        ElectricalLearnItPushButton->setObjectName(QString::fromUtf8("ElectricalLearnItPushButton"));
        ElectricalLearnItPushButton->setGeometry(QRect(170, 190, 211, 41));
        ElectricalLearnItPushButton->setFont(font);
        ElectricalLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        tabWidget->addTab(tab_13, QString());
        tab_14 = new QWidget();
        tab_14->setObjectName(QString::fromUtf8("tab_14"));
        bathTapsCheckBox = new QCheckBox(tab_14);
        bathTapsCheckBox->setObjectName(QString::fromUtf8("bathTapsCheckBox"));
        bathTapsCheckBox->setGeometry(QRect(130, 30, 341, 23));
        BathroomLearnItPushButton = new QPushButton(tab_14);
        BathroomLearnItPushButton->setObjectName(QString::fromUtf8("BathroomLearnItPushButton"));
        BathroomLearnItPushButton->setGeometry(QRect(130, 180, 211, 41));
        BathroomLearnItPushButton->setFont(font);
        BathroomLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        bathDoorCheckBox = new QCheckBox(tab_14);
        bathDoorCheckBox->setObjectName(QString::fromUtf8("bathDoorCheckBox"));
        bathDoorCheckBox->setGeometry(QRect(130, 80, 341, 23));
        bathFlushCheckBox = new QCheckBox(tab_14);
        bathFlushCheckBox->setObjectName(QString::fromUtf8("bathFlushCheckBox"));
        bathFlushCheckBox->setGeometry(QRect(130, 130, 341, 23));
        tabWidget->addTab(tab_14, QString());
        label_5 = new QLabel(tab_9);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 320, 411, 16));
        happeningSpinBox = new QSpinBox(tab_9);
        happeningSpinBox->setObjectName(QString::fromUtf8("happeningSpinBox"));
        happeningSpinBox->setGeometry(QRect(440, 310, 71, 31));
        label_11 = new QLabel(tab_9);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(520, 320, 91, 16));
        label_12 = new QLabel(tab_9);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 350, 391, 16));
        hasHappendedSpinBox = new QSpinBox(tab_9);
        hasHappendedSpinBox->setObjectName(QString::fromUtf8("hasHappendedSpinBox"));
        hasHappendedSpinBox->setGeometry(QRect(360, 340, 71, 31));
        label_21 = new QLabel(tab_9);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(440, 350, 41, 16));
        houseFinishedPushButton = new QPushButton(tab_9);
        houseFinishedPushButton->setObjectName(QString::fromUtf8("houseFinishedPushButton"));
        houseFinishedPushButton->setGeometry(QRect(490, 340, 191, 41));
        houseFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        houseFinishedPushButton->setCheckable(true);
        alreadyKnowWidget->addTab(tab_9, QString());
        tab_15 = new QWidget();
        tab_15->setObjectName(QString::fromUtf8("tab_15"));
        contextComboBox = new QComboBox(tab_15);
        contextComboBox->setObjectName(QString::fromUtf8("contextComboBox"));
        contextComboBox->setGeometry(QRect(210, 70, 461, 41));
        contextComboBox->setFont(font);
        contextComboBox->setEditable(false);
        label_15 = new QLabel(tab_15);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 80, 191, 16));
        contextLearnItPushButton = new QPushButton(tab_15);
        contextLearnItPushButton->setObjectName(QString::fromUtf8("contextLearnItPushButton"));
        contextLearnItPushButton->setGeometry(QRect(220, 290, 211, 41));
        contextLearnItPushButton->setFont(font);
        contextLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        contextFinishedPushButton = new QPushButton(tab_15);
        contextFinishedPushButton->setObjectName(QString::fromUtf8("contextFinishedPushButton"));
        contextFinishedPushButton->setGeometry(QRect(220, 340, 211, 41));
        contextFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        contextFinishedPushButton->setCheckable(true);
        label_20 = new QLabel(tab_15);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(70, 230, 331, 16));
        contextHappeningSpinBox = new QSpinBox(tab_15);
        contextHappeningSpinBox->setObjectName(QString::fromUtf8("contextHappeningSpinBox"));
        contextHappeningSpinBox->setGeometry(QRect(450, 180, 71, 31));
        label_29 = new QLabel(tab_15);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(70, 190, 371, 16));
        label_30 = new QLabel(tab_15);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(540, 190, 91, 16));
        label_31 = new QLabel(tab_15);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(540, 230, 91, 16));
        contextHasHappendedSpinBox = new QSpinBox(tab_15);
        contextHasHappendedSpinBox->setObjectName(QString::fromUtf8("contextHasHappendedSpinBox"));
        contextHasHappendedSpinBox->setGeometry(QRect(450, 220, 71, 31));
        alreadyKnowWidget->addTab(tab_15, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        label_9 = new QLabel(tab_7);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 180, 211, 31));
        label_10 = new QLabel(tab_7);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 240, 261, 31));
        label_13 = new QLabel(tab_7);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(0, 290, 191, 31));
        userLocnComboBox = new QComboBox(tab_7);
        userLocnComboBox->setObjectName(QString::fromUtf8("userLocnComboBox"));
        userLocnComboBox->setGeometry(QRect(200, 230, 481, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Sans Serif"));
        font1.setPointSize(14);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        font1.setKerning(true);
        userLocnComboBox->setFont(font1);
        andRobotLocnComboBox = new QComboBox(tab_7);
        andRobotLocnComboBox->setObjectName(QString::fromUtf8("andRobotLocnComboBox"));
        andRobotLocnComboBox->setGeometry(QRect(210, 280, 471, 41));
        locationLearnItPushButton = new QPushButton(tab_7);
        locationLearnItPushButton->setObjectName(QString::fromUtf8("locationLearnItPushButton"));
        locationLearnItPushButton->setGeometry(QRect(230, 330, 211, 41));
        locationLearnItPushButton->setFont(font);
        locationLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        locationListView = new QListView(tab_7);
        locationListView->setObjectName(QString::fromUtf8("locationListView"));
        locationListView->setGeometry(QRect(70, 30, 561, 121));
        knowHowLabel_8 = new QLabel(tab_7);
        knowHowLabel_8->setObjectName(QString::fromUtf8("knowHowLabel_8"));
        knowHowLabel_8->setGeometry(QRect(10, 10, 211, 16));
        knowHowLabel_8->setFont(font);
        locnFinishedPushButton = new QPushButton(tab_7);
        locnFinishedPushButton->setObjectName(QString::fromUtf8("locnFinishedPushButton"));
        locnFinishedPushButton->setGeometry(QRect(460, 330, 191, 41));
        locnFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        locnFinishedPushButton->setCheckable(true);
        alreadyKnowWidget->addTab(tab_7, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        timeLearnItPushButton = new QPushButton(tab_5);
        timeLearnItPushButton->setObjectName(QString::fromUtf8("timeLearnItPushButton"));
        timeLearnItPushButton->setGeometry(QRect(80, 300, 211, 41));
        timeLearnItPushButton->setFont(font);
        timeLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        label_7 = new QLabel(tab_5);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 30, 131, 16));
        label_8 = new QLabel(tab_5);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 80, 221, 16));
        AtTimeEdit = new QTimeEdit(tab_5);
        AtTimeEdit->setObjectName(QString::fromUtf8("AtTimeEdit"));
        AtTimeEdit->setGeometry(QRect(300, 20, 131, 31));
        betweenToTimeEdit = new QTimeEdit(tab_5);
        betweenToTimeEdit->setObjectName(QString::fromUtf8("betweenToTimeEdit"));
        betweenToTimeEdit->setGeometry(QRect(300, 100, 131, 31));
        betweenFromTimeEdit = new QTimeEdit(tab_5);
        betweenFromTimeEdit->setObjectName(QString::fromUtf8("betweenFromTimeEdit"));
        betweenFromTimeEdit->setGeometry(QRect(300, 70, 131, 31));
        groupBox = new QGroupBox(tab_5);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(250, 20, 41, 101));
        radioButton = new QRadioButton(groupBox);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(10, 10, 21, 21));
        radioButton_2 = new QRadioButton(groupBox);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(10, 40, 21, 21));
        radioButton_3 = new QRadioButton(groupBox);
        radioButton_3->setObjectName(QString::fromUtf8("radioButton_3"));
        radioButton_3->setGeometry(QRect(10, 70, 21, 21));
        groupBox_3 = new QGroupBox(groupBox);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 0, 41, 101));
        groupBox_3->setCheckable(false);
        atCheckBox = new QCheckBox(groupBox_3);
        atCheckBox->setObjectName(QString::fromUtf8("atCheckBox"));
        atCheckBox->setGeometry(QRect(10, 10, 21, 21));
        atCheckBox->setAutoExclusive(false);
        betweenCheckBox = new QCheckBox(groupBox_3);
        betweenCheckBox->setObjectName(QString::fromUtf8("betweenCheckBox"));
        betweenCheckBox->setGeometry(QRect(10, 60, 21, 21));
        betweenCheckBox->setAutoExclusive(false);
        groupBox_4 = new QGroupBox(groupBox_3);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(30, 180, 41, 181));
        radioButton_9 = new QRadioButton(groupBox_4);
        radioButton_9->setObjectName(QString::fromUtf8("radioButton_9"));
        radioButton_9->setGeometry(QRect(10, 10, 21, 21));
        radioButton_10 = new QRadioButton(groupBox_4);
        radioButton_10->setObjectName(QString::fromUtf8("radioButton_10"));
        radioButton_10->setGeometry(QRect(10, 40, 21, 21));
        radioButton_11 = new QRadioButton(groupBox_4);
        radioButton_11->setObjectName(QString::fromUtf8("radioButton_11"));
        radioButton_11->setGeometry(QRect(10, 70, 21, 21));
        radioButton_12 = new QRadioButton(groupBox_4);
        radioButton_12->setObjectName(QString::fromUtf8("radioButton_12"));
        radioButton_12->setGeometry(QRect(10, 130, 21, 21));
        label_4 = new QLabel(tab_5);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 140, 131, 16));
        groupBox_2 = new QGroupBox(tab_5);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 160, 651, 91));
        mondayCheckBox = new QCheckBox(groupBox_2);
        mondayCheckBox->setObjectName(QString::fromUtf8("mondayCheckBox"));
        mondayCheckBox->setGeometry(QRect(10, 10, 51, 21));
        tuesdayCheckBox = new QCheckBox(groupBox_2);
        tuesdayCheckBox->setObjectName(QString::fromUtf8("tuesdayCheckBox"));
        tuesdayCheckBox->setGeometry(QRect(60, 10, 51, 21));
        wednesdayCheckBox = new QCheckBox(groupBox_2);
        wednesdayCheckBox->setObjectName(QString::fromUtf8("wednesdayCheckBox"));
        wednesdayCheckBox->setGeometry(QRect(110, 10, 51, 21));
        ThursdayCheckBox = new QCheckBox(groupBox_2);
        ThursdayCheckBox->setObjectName(QString::fromUtf8("ThursdayCheckBox"));
        ThursdayCheckBox->setGeometry(QRect(160, 10, 51, 21));
        fridayCheckBox = new QCheckBox(groupBox_2);
        fridayCheckBox->setObjectName(QString::fromUtf8("fridayCheckBox"));
        fridayCheckBox->setGeometry(QRect(210, 10, 51, 21));
        saturdayCheckBox = new QCheckBox(groupBox_2);
        saturdayCheckBox->setObjectName(QString::fromUtf8("saturdayCheckBox"));
        saturdayCheckBox->setGeometry(QRect(260, 10, 51, 21));
        sundayCheckBox = new QCheckBox(groupBox_2);
        sundayCheckBox->setObjectName(QString::fromUtf8("sundayCheckBox"));
        sundayCheckBox->setGeometry(QRect(310, 10, 51, 21));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 70, 81, 16));
        everyNdaysSpinBox = new QSpinBox(groupBox_2);
        everyNdaysSpinBox->setObjectName(QString::fromUtf8("everyNdaysSpinBox"));
        everyNdaysSpinBox->setGeometry(QRect(90, 60, 71, 31));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(170, 70, 51, 16));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(260, 70, 81, 16));
        everyNHoursSpinBox = new QSpinBox(groupBox_2);
        everyNHoursSpinBox->setObjectName(QString::fromUtf8("everyNHoursSpinBox"));
        everyNHoursSpinBox->setGeometry(QRect(340, 60, 71, 31));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(420, 70, 61, 16));
        timeFinishedPushButton = new QPushButton(tab_5);
        timeFinishedPushButton->setObjectName(QString::fromUtf8("timeFinishedPushButton"));
        timeFinishedPushButton->setGeometry(QRect(380, 300, 191, 41));
        timeFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        timeFinishedPushButton->setCheckable(true);
        label_6 = new QLabel(tab_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(470, 30, 151, 16));
        line = new QFrame(tab_5);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(10, 250, 651, 16));
        line->setFont(font);
        line->setAutoFillBackground(false);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        alreadyKnowWidget->addTab(tab_5, QString());
        tab_18 = new QWidget();
        tab_18->setObjectName(QString::fromUtf8("tab_18"));
        label_24 = new QLabel(tab_18);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(780, 150, 41, 20));
        resetSpinBox = new QSpinBox(tab_18);
        resetSpinBox->setObjectName(QString::fromUtf8("resetSpinBox"));
        resetSpinBox->setGeometry(QRect(240, 220, 161, 31));
        resetSpinBox->setMaximum(1000000);
        resetSpinBox->setValue(60);
        alwaysCheckBox = new QCheckBox(tab_18);
        alwaysCheckBox->setObjectName(QString::fromUtf8("alwaysCheckBox"));
        alwaysCheckBox->setGeometry(QRect(110, 100, 361, 21));
        label_19 = new QLabel(tab_18);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(60, 50, 401, 16));
        label_25 = new QLabel(tab_18);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 170, 661, 16));
        label_26 = new QLabel(tab_18);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(130, 230, 91, 16));
        label_27 = new QLabel(tab_18);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(420, 220, 251, 20));
        repeatFinishedPushButton = new QPushButton(tab_18);
        repeatFinishedPushButton->setObjectName(QString::fromUtf8("repeatFinishedPushButton"));
        repeatFinishedPushButton->setGeometry(QRect(430, 320, 191, 41));
        repeatFinishedPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        repeatFinishedPushButton->setCheckable(true);
        repeatLearnItPushButton = new QPushButton(tab_18);
        repeatLearnItPushButton->setObjectName(QString::fromUtf8("repeatLearnItPushButton"));
        repeatLearnItPushButton->setGeometry(QRect(80, 320, 211, 41));
        repeatLearnItPushButton->setFont(font);
        repeatLearnItPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);"));
        alreadyKnowWidget->addTab(tab_18, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        label_14 = new QLabel(tab_8);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(20, 20, 291, 16));
        finalListView = new QListView(tab_8);
        finalListView->setObjectName(QString::fromUtf8("finalListView"));
        finalListView->setGeometry(QRect(30, 50, 611, 271));
        finalListView->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 128);\n"
"background-color: rgb(255, 255, 192);"));
        finalRememberPushButton = new QPushButton(tab_8);
        finalRememberPushButton->setObjectName(QString::fromUtf8("finalRememberPushButton"));
        finalRememberPushButton->setGeometry(QRect(120, 340, 451, 41));
        finalRememberPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        allDonePushButton = new QPushButton(tab_8);
        allDonePushButton->setObjectName(QString::fromUtf8("allDonePushButton"));
        allDonePushButton->setGeometry(QRect(240, 10, 411, 161));
        allDonePushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 243, 3);"));
        alreadyKnowWidget->addTab(tab_8, QString());
        learnedSoFarLabel = new QLabel(centralWidget);
        learnedSoFarLabel->setObjectName(QString::fromUtf8("learnedSoFarLabel"));
        learnedSoFarLabel->setEnabled(false);
        learnedSoFarLabel->setGeometry(QRect(810, 190, 291, 20));
        learnedSoFarLabel->setFont(font);
        learnedSoFarLabel->setAutoFillBackground(false);
        dbLabel = new QLabel(centralWidget);
        dbLabel->setObjectName(QString::fromUtf8("dbLabel"));
        dbLabel->setGeometry(QRect(60, 680, 1011, 16));
        behNameComboBox = new QComboBox(centralWidget);
        behNameComboBox->setObjectName(QString::fromUtf8("behNameComboBox"));
        behNameComboBox->setGeometry(QRect(430, 0, 251, 41));
        behNameComboBox->setFont(font);
        behNameComboBox->setEditable(true);
        addPushButton = new QPushButton(centralWidget);
        addPushButton->setObjectName(QString::fromUtf8("addPushButton"));
        addPushButton->setGeometry(QRect(680, 0, 211, 41));
        addPushButton->setFont(font);
        addPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 192, 0);\n"
"color: rgb(0, 0, 0);"));
        deletePushButton = new QPushButton(centralWidget);
        deletePushButton->setObjectName(QString::fromUtf8("deletePushButton"));
        deletePushButton->setGeometry(QRect(680, 0, 211, 41));
        deletePushButton->setFont(font);
        deletePushButton->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);"));
        rememberThisPushButton = new QPushButton(centralWidget);
        rememberThisPushButton->setObjectName(QString::fromUtf8("rememberThisPushButton"));
        rememberThisPushButton->setGeometry(QRect(80, 600, 561, 41));
        rememberThisPushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(231, 255, 11);\n"
"color: rgb(0, 0, 0);"));
        behNameLineEdit = new QLineEdit(centralWidget);
        behNameLineEdit->setObjectName(QString::fromUtf8("behNameLineEdit"));
        behNameLineEdit->setGeometry(QRect(20, 50, 661, 41));
        learnedSoFarListWidget = new QListWidget(centralWidget);
        learnedSoFarListWidget->setObjectName(QString::fromUtf8("learnedSoFarListWidget"));
        learnedSoFarListWidget->setGeometry(QRect(740, 221, 331, 361));
        learnedSoFarListWidget->setEditTriggers(QAbstractItemView::NoEditTriggers);
        learnedSoFarListWidget->setDragEnabled(true);
        learnedSoFarListWidget->setDragDropOverwriteMode(true);
        learnedSoFarListWidget->setDragDropMode(QAbstractItemView::DragDrop);
        learnedSoFarListWidget->setDefaultDropAction(Qt::MoveAction);
        nickName = new QLabel(centralWidget);
        nickName->setObjectName(QString::fromUtf8("nickName"));
        nickName->setGeometry(QRect(130, 10, 241, 16));
        whatPushButton = new QPushButton(centralWidget);
        whatPushButton->setObjectName(QString::fromUtf8("whatPushButton"));
        whatPushButton->setEnabled(false);
        whatPushButton->setGeometry(QRect(20, 100, 281, 51));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(220, 220, 220, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(138, 255, 83, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(106, 237, 45, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(37, 110, 3, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(50, 147, 4, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(165, 237, 131, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush9(QColor(75, 220, 7, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        whatPushButton->setPalette(palette);
        whenPushButton = new QPushButton(centralWidget);
        whenPushButton->setObjectName(QString::fromUtf8("whenPushButton"));
        whenPushButton->setEnabled(false);
        whenPushButton->setGeometry(QRect(350, 100, 301, 51));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush10(QColor(194, 255, 166, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush10);
        QBrush brush11(QColor(158, 237, 122, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        QBrush brush12(QColor(61, 110, 39, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(82, 147, 52, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush14(QColor(189, 237, 166, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush15(QColor(123, 220, 78, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        whenPushButton->setPalette(palette1);
        whatPushButton_2 = new QPushButton(centralWidget);
        whatPushButton_2->setObjectName(QString::fromUtf8("whatPushButton_2"));
        whatPushButton_2->setEnabled(false);
        whatPushButton_2->setGeometry(QRect(20, 100, 301, 51));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush16(QColor(240, 240, 240, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush16);
        QBrush brush17(QColor(200, 200, 200, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        QBrush brush18(QColor(80, 80, 80, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush18);
        QBrush brush19(QColor(107, 107, 107, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush20(QColor(207, 207, 207, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush20);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush17);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush19);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush21(QColor(160, 160, 160, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        whatPushButton_2->setPalette(palette2);
        whatPushButton_2->setCheckable(true);
        whatPushButton_2->setChecked(true);
        whenPushButton_2 = new QPushButton(centralWidget);
        whenPushButton_2->setObjectName(QString::fromUtf8("whenPushButton_2"));
        whenPushButton_2->setEnabled(false);
        whenPushButton_2->setGeometry(QRect(350, 100, 321, 51));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush22(QColor(224, 224, 224, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush22);
        QBrush brush23(QColor(186, 186, 186, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush23);
        QBrush brush24(QColor(74, 74, 74, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush24);
        QBrush brush25(QColor(99, 99, 99, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush26(QColor(202, 202, 202, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush26);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush22);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush23);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush24);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush26);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush22);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush27(QColor(149, 149, 149, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        whenPushButton_2->setPalette(palette3);
        whenPushButton_2->setCheckable(true);
        whenPushButton_2->setChecked(true);
        arrow1 = new QLabel(centralWidget);
        arrow1->setObjectName(QString::fromUtf8("arrow1"));
        arrow1->setGeometry(QRect(320, 120, 31, 16));
        finishedB = new QPushButton(centralWidget);
        finishedB->setObjectName(QString::fromUtf8("finishedB"));
        finishedB->setEnabled(false);
        finishedB->setGeometry(QRect(700, 100, 301, 51));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        finishedB->setPalette(palette4);
        finsihedB2 = new QPushButton(centralWidget);
        finsihedB2->setObjectName(QString::fromUtf8("finsihedB2"));
        finsihedB2->setEnabled(false);
        finsihedB2->setGeometry(QRect(700, 100, 301, 51));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush22);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush23);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush24);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush25);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush26);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush22);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush23);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush24);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush25);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush26);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush24);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush22);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush23);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush24);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush25);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush24);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush24);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush27);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        finsihedB2->setPalette(palette5);
        finsihedB2->setCheckable(true);
        finsihedB2->setChecked(true);
        arrow2 = new QLabel(centralWidget);
        arrow2->setObjectName(QString::fromUtf8("arrow2"));
        arrow2->setGeometry(QRect(670, 120, 31, 16));
        changePushButton = new QPushButton(centralWidget);
        changePushButton->setObjectName(QString::fromUtf8("changePushButton"));
        changePushButton->setGeometry(QRect(900, 0, 221, 41));
        changePushButton->setFont(font);
        changePushButton->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);"));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1129, 27));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        alreadyKnowWidget->setCurrentIndex(8);
        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Teach Me - Show me", 0, QApplication::UnicodeUTF8));
        teachMePushButton->setText(QApplication::translate("MainWindow", "Teach Me How To..", 0, QApplication::UnicodeUTF8));
        showMePushButton->setText(QApplication::translate("MainWindow", "Show Me What is...", 0, QApplication::UnicodeUTF8));
        startLearningPushButton->setText(QApplication::translate("MainWindow", "Start Learning", 0, QApplication::UnicodeUTF8));
        stopLearningPushButton->setText(QApplication::translate("MainWindow", "Enter what do you want the robot to do below", 0, QApplication::UnicodeUTF8));
        cancelPushButton->setText(QApplication::translate("MainWindow", "or Start Again", 0, QApplication::UnicodeUTF8));
        learningStartedLabel->setText(QString());
        knowHowLabel->setText(QApplication::translate("MainWindow", "I already know how to...", 0, QApplication::UnicodeUTF8));
        everythingLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab), QApplication::translate("MainWindow", "Things I've been taught", 0, QApplication::UnicodeUTF8));
        knowHowLabel_4->setText(QApplication::translate("MainWindow", "I already know how to...", 0, QApplication::UnicodeUTF8));
        moveLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Or move the robot to the", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Moving", 0, QApplication::UnicodeUTF8));
        knowHowLabel_2->setText(QApplication::translate("MainWindow", "I already know how to...", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Or say something new->", 0, QApplication::UnicodeUTF8));
        speakLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Speaking", 0, QApplication::UnicodeUTF8));
        knowHowLabel_5->setText(QApplication::translate("MainWindow", "I already know how to...", 0, QApplication::UnicodeUTF8));
        trayLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_17), QApplication::translate("MainWindow", "My tray and body", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_6), QApplication::translate("MainWindow", "Using My Arm", 0, QApplication::UnicodeUTF8));
        whenTellMePushButton->setText(QApplication::translate("MainWindow", "only when you tell me to?", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Shall I do this...", 0, QApplication::UnicodeUTF8));
        whenSomethingPushButton->setText(QApplication::translate("MainWindow", "when something happens in the house?", 0, QApplication::UnicodeUTF8));
        doingPushButton->setText(QApplication::translate("MainWindow", "when I'm doing something in particular?", 0, QApplication::UnicodeUTF8));
        locationPushButton->setText(QApplication::translate("MainWindow", "when you or I are in a particular part of the house?", 0, QApplication::UnicodeUTF8));
        timePushButton->setText(QApplication::translate("MainWindow", "at a particular time or day?", 0, QApplication::UnicodeUTF8));
        okPushButton->setText(QApplication::translate("MainWindow", "OK", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_3), QApplication::translate("MainWindow", "When and Why?", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "OK  -  I'll display the choice on your tablet!", 0, QApplication::UnicodeUTF8));
        toldFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished?", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_16), QApplication::translate("MainWindow", "Tablet", 0, QApplication::UnicodeUTF8));
        sittingTableCheckBox->setText(QApplication::translate("MainWindow", "Someone sitting at the table?", 0, QApplication::UnicodeUTF8));
        bigCupboardCheckBox->setText(QApplication::translate("MainWindow", "Big Cupboard doors or drawers are open?", 0, QApplication::UnicodeUTF8));
        smallCupboardCheckBox->setText(QApplication::translate("MainWindow", "Small Cupboard doors or drawers are open?", 0, QApplication::UnicodeUTF8));
        diningLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_10), QApplication::translate("MainWindow", "Dining Room", 0, QApplication::UnicodeUTF8));
        sittingSofaCheckBox->setText(QApplication::translate("MainWindow", "Someone sitting at the sofa?", 0, QApplication::UnicodeUTF8));
        TVOncheckBox->setText(QApplication::translate("MainWindow", "TV is on?", 0, QApplication::UnicodeUTF8));
        livingLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_11), QApplication::translate("MainWindow", "Living Room", 0, QApplication::UnicodeUTF8));
        kitechCupboadsCheckBox->setText(QApplication::translate("MainWindow", "Cupboards or drawers are open?", 0, QApplication::UnicodeUTF8));
        kitchenTapsCheckBox->setText(QApplication::translate("MainWindow", "Taps are running?", 0, QApplication::UnicodeUTF8));
        kitchenLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_12), QApplication::translate("MainWindow", "Kitchen", 0, QApplication::UnicodeUTF8));
        microwaveCheckBox->setText(QApplication::translate("MainWindow", "Microwave, cooker or toaster are on?", 0, QApplication::UnicodeUTF8));
        fridgeCheckBox->setText(QApplication::translate("MainWindow", "Fridge open, kettle or dishwasher are on?", 0, QApplication::UnicodeUTF8));
        doorbellCheckBox->setText(QApplication::translate("MainWindow", "Doorbell has rung?", 0, QApplication::UnicodeUTF8));
        ElectricalLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_13), QApplication::translate("MainWindow", "Electrical", 0, QApplication::UnicodeUTF8));
        bathTapsCheckBox->setText(QApplication::translate("MainWindow", "Taps are running?", 0, QApplication::UnicodeUTF8));
        BathroomLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        bathDoorCheckBox->setText(QApplication::translate("MainWindow", "Bathroom Door Closed", 0, QApplication::UnicodeUTF8));
        bathFlushCheckBox->setText(QApplication::translate("MainWindow", "Toilet Flushed", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_14), QApplication::translate("MainWindow", "Bathroom", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "And this has been happening for more than", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "Minutes", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "Or this has happened within the last ", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "Min.", 0, QApplication::UnicodeUTF8));
        houseFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished this part?", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_9), QApplication::translate("MainWindow", "House", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "When this happens", 0, QApplication::UnicodeUTF8));
        contextLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        contextFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished this part?", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "Or this has happened within the last ", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "And this has been happening for more than", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "Minutes", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "Minute(s)", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_15), QApplication::translate("MainWindow", "Activities", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Only do this when...", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "I am here ->", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "The robot is  here ->", 0, QApplication::UnicodeUTF8));
        locationLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        knowHowLabel_8->setText(QApplication::translate("MainWindow", "I already know...", 0, QApplication::UnicodeUTF8));
        locnFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished this part?", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_7), QApplication::translate("MainWindow", "Location", 0, QApplication::UnicodeUTF8));
        timeLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "At this time ->", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "Between these times  ->", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QString());
        radioButton->setText(QString());
        radioButton_2->setText(QString());
        radioButton_3->setText(QString());
        groupBox_3->setTitle(QString());
        atCheckBox->setText(QString());
        betweenCheckBox->setText(QString());
        groupBox_4->setTitle(QString());
        radioButton_9->setText(QString());
        radioButton_10->setText(QString());
        radioButton_11->setText(QString());
        radioButton_12->setText(QString());
        label_4->setText(QApplication::translate("MainWindow", "On these days", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QString());
        mondayCheckBox->setText(QApplication::translate("MainWindow", "M", 0, QApplication::UnicodeUTF8));
        tuesdayCheckBox->setText(QApplication::translate("MainWindow", "T", 0, QApplication::UnicodeUTF8));
        wednesdayCheckBox->setText(QApplication::translate("MainWindow", "W", 0, QApplication::UnicodeUTF8));
        ThursdayCheckBox->setText(QApplication::translate("MainWindow", "T", 0, QApplication::UnicodeUTF8));
        fridayCheckBox->setText(QApplication::translate("MainWindow", "F", 0, QApplication::UnicodeUTF8));
        saturdayCheckBox->setText(QApplication::translate("MainWindow", "S", 0, QApplication::UnicodeUTF8));
        sundayCheckBox->setText(QApplication::translate("MainWindow", "S", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "Every", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "Days", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "or Every", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "Hours", 0, QApplication::UnicodeUTF8));
        timeFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished this part?", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "(or start time)", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_5), QApplication::translate("MainWindow", "When", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "secs", 0, QApplication::UnicodeUTF8));
        alwaysCheckBox->setText(QApplication::translate("MainWindow", "Shall I do this only once per day?", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "One final question...", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "Or shall I repeat this whenever necessary, after waiting  a little while?", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "Wait for", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "secs before doing it again", 0, QApplication::UnicodeUTF8));
        repeatFinishedPushButton->setText(QApplication::translate("MainWindow", "Finished this part?", 0, QApplication::UnicodeUTF8));
        repeatLearnItPushButton->setText(QApplication::translate("MainWindow", "Learn It!", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_18), QApplication::translate("MainWindow", "Repeat", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "This is what I've learned:", 0, QApplication::UnicodeUTF8));
        finalRememberPushButton->setText(QApplication::translate("MainWindow", "Make the robot do this from now on", 0, QApplication::UnicodeUTF8));
        allDonePushButton->setText(QApplication::translate("MainWindow", "I have scheduled this - press me to continue", 0, QApplication::UnicodeUTF8));
        alreadyKnowWidget->setTabText(alreadyKnowWidget->indexOf(tab_8), QApplication::translate("MainWindow", "Finish", 0, QApplication::UnicodeUTF8));
        learnedSoFarLabel->setText(QApplication::translate("MainWindow", "What I've learned so far", 0, QApplication::UnicodeUTF8));
        dbLabel->setText(QString());
        addPushButton->setText(QApplication::translate("MainWindow", "Make me learn this?", 0, QApplication::UnicodeUTF8));
        deletePushButton->setText(QApplication::translate("MainWindow", "Make me forget this?", 0, QApplication::UnicodeUTF8));
        rememberThisPushButton->setText(QApplication::translate("MainWindow", "Click me when finished WHAT phase", 0, QApplication::UnicodeUTF8));
        behNameLineEdit->setText(QApplication::translate("MainWindow", "Say what you want the robot to do  in here", 0, QApplication::UnicodeUTF8));
        nickName->setText(QApplication::translate("MainWindow", "Give a nickname here >>", 0, QApplication::UnicodeUTF8));
        whatPushButton->setText(QApplication::translate("MainWindow", "1. WHAT should the robot do?", 0, QApplication::UnicodeUTF8));
        whenPushButton->setText(QApplication::translate("MainWindow", "2. WHEN should the robot do it?", 0, QApplication::UnicodeUTF8));
        whatPushButton_2->setText(QApplication::translate("MainWindow", "1. WHAT should the robot do?", 0, QApplication::UnicodeUTF8));
        whenPushButton_2->setText(QApplication::translate("MainWindow", "2. WHEN should the robot do it?", 0, QApplication::UnicodeUTF8));
        arrow1->setText(QApplication::translate("MainWindow", "-->", 0, QApplication::UnicodeUTF8));
        finishedB->setText(QApplication::translate("MainWindow", "3. FINISHED teaching", 0, QApplication::UnicodeUTF8));
        finsihedB2->setText(QApplication::translate("MainWindow", "3. FINISHED teaching", 0, QApplication::UnicodeUTF8));
        arrow2->setText(QApplication::translate("MainWindow", "-->", 0, QApplication::UnicodeUTF8));
        changePushButton->setText(QApplication::translate("MainWindow", "Make me change this?", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
